/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as DashboardEmployeeRouteImport } from './routes/dashboard/employee'
import { Route as EmployeeIndexRouteImport } from './routes/employee.index'
import { Route as EmployeeAttendanceRouteImport } from './routes/employee.attendance'
import { Route as EmployeeLeaveRouteImport } from './routes/employee.leave'
import { Route as EmployeeNotificationsRouteImport } from './routes/employee.notifications'
import { Route as EmployeePayrollRouteImport } from './routes/employee.payroll'
import { Route as EmployeeProfileRouteImport } from './routes/employee.profile'
import { Route as EmployeeSettingsRouteImport } from './routes/employee.settings'
import { Route as HrIndexRouteImport } from './routes/hr.index'
import { Route as HrApprovalsRouteImport } from './routes/hr.approvals'
import { Route as HrAttendanceRouteImport } from './routes/hr.attendance'
import { Route as HrEmployeesRouteImport } from './routes/hr.employees'
import { Route as HrNotificationsRouteImport } from './routes/hr.notifications'
import { Route as HrPayrollRouteImport } from './routes/hr.payroll'
import { Route as HrReportsRouteImport } from './routes/hr.reports'
import { Route as HrSettingsRouteImport } from './routes/hr.settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEmployeeRoute = DashboardEmployeeRouteImport.update({
  id: '/dashboard/employee',
  path: '/dashboard/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeIndexRoute = EmployeeIndexRouteImport.update({
  id: '/employee/',
  path: '/employee/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeAttendanceRoute = EmployeeAttendanceRouteImport.update({
  id: '/employee/attendance',
  path: '/employee/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeLeaveRoute = EmployeeLeaveRouteImport.update({
  id: '/employee/leave',
  path: '/employee/leave',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeNotificationsRoute = EmployeeNotificationsRouteImport.update({
  id: '/employee/notifications',
  path: '/employee/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeePayrollRoute = EmployeePayrollRouteImport.update({
  id: '/employee/payroll',
  path: '/employee/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeProfileRoute = EmployeeProfileRouteImport.update({
  id: '/employee/profile',
  path: '/employee/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeSettingsRoute = EmployeeSettingsRouteImport.update({
  id: '/employee/settings',
  path: '/employee/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const HrIndexRoute = HrIndexRouteImport.update({
  id: '/hr/',
  path: '/hr/',
  getParentRoute: () => rootRouteImport,
} as any)
const HrApprovalsRoute = HrApprovalsRouteImport.update({
  id: '/hr/approvals',
  path: '/hr/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const HrAttendanceRoute = HrAttendanceRouteImport.update({
  id: '/hr/attendance',
  path: '/hr/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const HrEmployeesRoute = HrEmployeesRouteImport.update({
  id: '/hr/employees',
  path: '/hr/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const HrNotificationsRoute = HrNotificationsRouteImport.update({
  id: '/hr/notifications',
  path: '/hr/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const HrPayrollRoute = HrPayrollRouteImport.update({
  id: '/hr/payroll',
  path: '/hr/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const HrReportsRoute = HrReportsRouteImport.update({
  id: '/hr/reports',
  path: '/hr/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const HrSettingsRoute = HrSettingsRouteImport.update({
  id: '/hr/settings',
  path: '/hr/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/dashboard/employee': typeof DashboardEmployeeRoute
  '/employee/attendance': typeof EmployeeAttendanceRoute
  '/employee/leave': typeof EmployeeLeaveRoute
  '/employee/notifications': typeof EmployeeNotificationsRoute
  '/employee/payroll': typeof EmployeePayrollRoute
  '/employee/profile': typeof EmployeeProfileRoute
  '/employee/settings': typeof EmployeeSettingsRoute
  '/hr/approvals': typeof HrApprovalsRoute
  '/hr/attendance': typeof HrAttendanceRoute
  '/hr/employees': typeof HrEmployeesRoute
  '/hr/notifications': typeof HrNotificationsRoute
  '/hr/payroll': typeof HrPayrollRoute
  '/hr/reports': typeof HrReportsRoute
  '/hr/settings': typeof HrSettingsRoute
  '/employee/': typeof EmployeeIndexRoute
  '/hr/': typeof HrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/dashboard/employee': typeof DashboardEmployeeRoute
  '/employee/attendance': typeof EmployeeAttendanceRoute
  '/employee/leave': typeof EmployeeLeaveRoute
  '/employee/notifications': typeof EmployeeNotificationsRoute
  '/employee/payroll': typeof EmployeePayrollRoute
  '/employee/profile': typeof EmployeeProfileRoute
  '/employee/settings': typeof EmployeeSettingsRoute
  '/hr/approvals': typeof HrApprovalsRoute
  '/hr/attendance': typeof HrAttendanceRoute
  '/hr/employees': typeof HrEmployeesRoute
  '/hr/notifications': typeof HrNotificationsRoute
  '/hr/payroll': typeof HrPayrollRoute
  '/hr/reports': typeof HrReportsRoute
  '/hr/settings': typeof HrSettingsRoute
  '/employee': typeof EmployeeIndexRoute
  '/hr': typeof HrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/dashboard/employee': typeof DashboardEmployeeRoute
  '/employee/attendance': typeof EmployeeAttendanceRoute
  '/employee/leave': typeof EmployeeLeaveRoute
  '/employee/notifications': typeof EmployeeNotificationsRoute
  '/employee/payroll': typeof EmployeePayrollRoute
  '/employee/profile': typeof EmployeeProfileRoute
  '/employee/settings': typeof EmployeeSettingsRoute
  '/hr/approvals': typeof HrApprovalsRoute
  '/hr/attendance': typeof HrAttendanceRoute
  '/hr/employees': typeof HrEmployeesRoute
  '/hr/notifications': typeof HrNotificationsRoute
  '/hr/payroll': typeof HrPayrollRoute
  '/hr/reports': typeof HrReportsRoute
  '/hr/settings': typeof HrSettingsRoute
  '/employee/': typeof EmployeeIndexRoute
  '/hr/': typeof HrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/dashboard/employee'
    | '/employee/attendance'
    | '/employee/leave'
    | '/employee/notifications'
    | '/employee/payroll'
    | '/employee/profile'
    | '/employee/settings'
    | '/hr/approvals'
    | '/hr/attendance'
    | '/hr/employees'
    | '/hr/notifications'
    | '/hr/payroll'
    | '/hr/reports'
    | '/hr/settings'
    | '/employee/'
    | '/hr/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/dashboard/employee'
    | '/employee/attendance'
    | '/employee/leave'
    | '/employee/notifications'
    | '/employee/payroll'
    | '/employee/profile'
    | '/employee/settings'
    | '/hr/approvals'
    | '/hr/attendance'
    | '/hr/employees'
    | '/hr/notifications'
    | '/hr/payroll'
    | '/hr/reports'
    | '/hr/settings'
    | '/employee'
    | '/hr'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/dashboard/employee'
    | '/employee/attendance'
    | '/employee/leave'
    | '/employee/notifications'
    | '/employee/payroll'
    | '/employee/profile'
    | '/employee/settings'
    | '/hr/approvals'
    | '/hr/attendance'
    | '/hr/employees'
    | '/hr/notifications'
    | '/hr/payroll'
    | '/hr/reports'
    | '/hr/settings'
    | '/employee/'
    | '/hr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  DashboardEmployeeRoute: typeof DashboardEmployeeRoute
  EmployeeAttendanceRoute: typeof EmployeeAttendanceRoute
  EmployeeLeaveRoute: typeof EmployeeLeaveRoute
  EmployeeNotificationsRoute: typeof EmployeeNotificationsRoute
  EmployeePayrollRoute: typeof EmployeePayrollRoute
  EmployeeProfileRoute: typeof EmployeeProfileRoute
  EmployeeSettingsRoute: typeof EmployeeSettingsRoute
  HrApprovalsRoute: typeof HrApprovalsRoute
  HrAttendanceRoute: typeof HrAttendanceRoute
  HrEmployeesRoute: typeof HrEmployeesRoute
  HrNotificationsRoute: typeof HrNotificationsRoute
  HrPayrollRoute: typeof HrPayrollRoute
  HrReportsRoute: typeof HrReportsRoute
  HrSettingsRoute: typeof HrSettingsRoute
  EmployeeIndexRoute: typeof EmployeeIndexRoute
  HrIndexRoute: typeof HrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/employee': {
      id: '/dashboard/employee'
      path: '/dashboard/employee'
      fullPath: '/dashboard/employee'
      preLoaderRoute: typeof DashboardEmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/': {
      id: '/employee/'
      path: '/employee'
      fullPath: '/employee/'
      preLoaderRoute: typeof EmployeeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/attendance': {
      id: '/employee/attendance'
      path: '/employee/attendance'
      fullPath: '/employee/attendance'
      preLoaderRoute: typeof EmployeeAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/leave': {
      id: '/employee/leave'
      path: '/employee/leave'
      fullPath: '/employee/leave'
      preLoaderRoute: typeof EmployeeLeaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/notifications': {
      id: '/employee/notifications'
      path: '/employee/notifications'
      fullPath: '/employee/notifications'
      preLoaderRoute: typeof EmployeeNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/payroll': {
      id: '/employee/payroll'
      path: '/employee/payroll'
      fullPath: '/employee/payroll'
      preLoaderRoute: typeof EmployeePayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/profile': {
      id: '/employee/profile'
      path: '/employee/profile'
      fullPath: '/employee/profile'
      preLoaderRoute: typeof EmployeeProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/settings': {
      id: '/employee/settings'
      path: '/employee/settings'
      fullPath: '/employee/settings'
      preLoaderRoute: typeof EmployeeSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/': {
      id: '/hr/'
      path: '/hr'
      fullPath: '/hr/'
      preLoaderRoute: typeof HrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/approvals': {
      id: '/hr/approvals'
      path: '/hr/approvals'
      fullPath: '/hr/approvals'
      preLoaderRoute: typeof HrApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/attendance': {
      id: '/hr/attendance'
      path: '/hr/attendance'
      fullPath: '/hr/attendance'
      preLoaderRoute: typeof HrAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/employees': {
      id: '/hr/employees'
      path: '/hr/employees'
      fullPath: '/hr/employees'
      preLoaderRoute: typeof HrEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/notifications': {
      id: '/hr/notifications'
      path: '/hr/notifications'
      fullPath: '/hr/notifications'
      preLoaderRoute: typeof HrNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/payroll': {
      id: '/hr/payroll'
      path: '/hr/payroll'
      fullPath: '/hr/payroll'
      preLoaderRoute: typeof HrPayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/reports': {
      id: '/hr/reports'
      path: '/hr/reports'
      fullPath: '/hr/reports'
      preLoaderRoute: typeof HrReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/settings': {
      id: '/hr/settings'
      path: '/hr/settings'
      fullPath: '/hr/settings'
      preLoaderRoute: typeof HrSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  DashboardEmployeeRoute: DashboardEmployeeRoute,
  EmployeeAttendanceRoute: EmployeeAttendanceRoute,
  EmployeeLeaveRoute: EmployeeLeaveRoute,
  EmployeeNotificationsRoute: EmployeeNotificationsRoute,
  EmployeePayrollRoute: EmployeePayrollRoute,
  EmployeeProfileRoute: EmployeeProfileRoute,
  EmployeeSettingsRoute: EmployeeSettingsRoute,
  HrApprovalsRoute: HrApprovalsRoute,
  HrAttendanceRoute: HrAttendanceRoute,
  HrEmployeesRoute: HrEmployeesRoute,
  HrNotificationsRoute: HrNotificationsRoute,
  HrPayrollRoute: HrPayrollRoute,
  HrReportsRoute: HrReportsRoute,
  HrSettingsRoute: HrSettingsRoute,
  EmployeeIndexRoute: EmployeeIndexRoute,
  HrIndexRoute: HrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
